/* **************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the graphql-starter-template repository.
  Changes made to this file inside child repos will NOT be reflected in the parent source
  template repository, and will interfere with the ability to upgrade common code from
  the template repository.
***************************************************************************************** */
const { ApolloServer } = require('apollo-server-express');
const express = require('express');
const session = require('express-session');
const cors = require('cors');
const cache = require('coa-web-cache');
const { checkLogin } = require('coa-web-login');
const MemoryStore = require('memorystore')(session);

require('dotenv').config();
const apiConfig = require('./api/config');
const getDbConnection = require('./common/db');

const getUserInfo = require('./common/get_user_info');

const GRAPHQL_PORT = process.env.PORT || 4000;

const app = express();

let sessionCache = null;
const cacheMethod = process.env.cache_method || 'memory';
if (cacheMethod === 'memory') {
  sessionCache = new MemoryStore({
    checkPeriod: 86400000, // prune expired entries every 24h
  });
} else {
  throw new Error('Redis caching not yet implemented');
}

// Initialize session management
app.use(session({
  name: process.env.sessionName,
  secret: process.env.sessionSecret,
  resave: false,
  saveUninitialized: true,
  store: sessionCache,
  cookie: {
    httpOnly: true,
    secure: 'auto',
    maxAge: 1000 * 60 * 60 * 24 * process.env.maxSessionDays,
  },
}));

// Set up CORS
const corsOptions = {
  origin: 'http://localhost:3000',
  credentials: true,
};
app.use(cors(corsOptions));


if (apiConfig.enableEmployeeLogins) {
  getDbConnection('mds'); // Initialize the connection.
}

// Check whether the user is logged in
app.use((req, res, next) => {
  cache.get(req.session.id)
    .then((sessionId) => {
      checkLogin(req, sessionId, cache)
        .then(isLoggedIn => getUserInfo(isLoggedIn, apiConfig, req, cache))
        .then((uinfo) => {
          req.session.employee_id = uinfo.id;
          return next();
        })
        .catch((err) => {
          const error = new Error(err.toString().substring(6));
          error.httpStatusCode = 403;
          error.stack = null;
          return next(error);
        });
    });
});

// Add in any middleware defined by the API
require('./api').middlewares.forEach((m) => { app.use(m); });

// Now configure and apply the GraphQL server

const typeDefs = require('./schema');
const resolvers = require('./resolvers');

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ req }) => ({
    session: req.session,
    req,
    cache,
  }),
});

server.applyMiddleware({ app, cors: corsOptions });

// And off we go!
app.listen({ port: GRAPHQL_PORT }, () => {
  console.log(`Server ready at http://localhost:${GRAPHQL_PORT}${server.graphqlPath}`);
});
